### ISSUE TITLE
Tracking issue for axum 0.6.X migration

### ISSUE THREAD

**Issue by blaenk** [Altair-Bueno/axum-template#14]
I'm sure you're already aware but either way may be useful to have a tracking issue for this.

Changelog including breaking changes available [here](https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md#060-25-november-2022).

Thank you for this crate!

**Comment by Altair-Bueno** [comment]
`axum-template` 0.10.0 adds support for `axum` 0.6.X. 

- Changelog and migration guide: https://github.com/Altair-Bueno/axum-template/releases/tag/v0.10.0. 
- Crates.io: https://crates.io/crates/axum-template/0.10.0
- docs.rs : https://docs.rs/axum-template/0.10.0/axum_template/

Please let me know if you find any bugs or outdated docs related to axum 0.5.X on this release ^_^

**Comment by blaenk** [comment]
Worked great! Thank you for the superb documentation and migration guide/diffs!
