### ISSUE TITLE
Use Tera Context for data instead of struct

### ISSUE THREAD

**Issue by EraYaN** [Altair-Bueno/axum-template#34]
Would it be possible to enable RenderHtml to accept the Tera Context instead of a struct? Some handlers might need to return RenderHtml with different templates (and thus different Models) and as far an I can see that won't work.

**Comment by Altair-Bueno** [comment]
I don't fully understand your question. Could you please provide an example of what you are trying to accomplish?

> Some handlers might need to return RenderHtml with different templates (and thus different Models) and as far an I can see that won't work.

```rs
fn foo(engine: AppEngine) -> impl IntoResponse {
  // Won't compile because `if` and `else` have incompatible types
  if rand::random() {
    RenderHtml("one", engine, &data1)
  } else {
    RenderHtml("two", engine, &data2)
  }
}
```

```rs
fn foo(engine: AppEngine) -> Response {
  if rand::random() {
    RenderHtml("one", engine, &data1).into_response()
  } else {
    RenderHtml("two", engine, &data2).into_response()
  }
}
```

**Comment by EraYaN** [comment]
```rust
use tera::Context;

let mut context = Context::new();

context.insert("barcode", &item);

RenderHtml("one", engine, &data1).into_response()
```

This allows to use RenderHtml calls (in an if for example) in the same handler with different context variables.

**Comment by Altair-Bueno** [comment]
Context is nothing but a wrapper around `serde_json::Value`, which implements serializable. You can transform into the inner type by using [into_json](https://docs.rs/tera/latest/tera/struct.Context.html#method.into_json)

However I would suggest you do not use `tera::Context` but rather `serde_json::Value` or similar, as it would lock your application to tera and wouldn't allow for an easy engine switch if you later decide so. The idea behind axum-template is to simplify template usage no matter the engine used, similar to spring web and other frameworks, without locking in to certain conventions.

**Comment by EraYaN** [comment]
Aah I didn't know I could potentially use `serde_json::Value`, I was just playing with some [speedtests](https://github.com/EraYaN/speedtests) and it needed to return a 404 with a different model. But I'll look into adding this crate back in. I'll close this for now.

**Comment by Altair-Bueno** [comment]
> it needed to return a 404 with a different model

In that case you could also return a `Result::Err` with said error. Result impl IntoResponse

`(StatusCode::NOT_FOUND,RenderHtml("notfound",engine,data))`
